### ISSUE TITLE
Transaction.close causes coredump

### ISSUE THREAD

**Issue by purplefox** [deephacks/lmdbjni#78] opened 2016-11-18 10:07 UTC
I've been seeing intermittent core dumps when running our tests with lmdb-jni in a loop:

~~~~
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f12047fff5f, pid=28581, tid=0x00007f11febef700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [liblmdbjni-64-0-2873664317511820691.4+0x1ff5f]  mdb_txn_end+0x10f
~~~~

This seems to be caused by tx.close() being called in our code here:

https://github.com/Tesco/mewbase/blob/doc_query/src/main/java/com/tesco/mewbase/doc/impl/lmdb/LmdbDocManager.java#L216

Looking in the log, this seems to be happening in mdb_tx_end native code:

~~~~
Stack: [0x00007f11feaef000,0x00007f11febf0000],  sp=0x00007f11febee2b0,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [liblmdbjni-64-0-2873664317511820691.4+0x1ff5f]  mdb_txn_end+0x10f

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.fusesource.lmdbjni.JNI.mdb_txn_abort(J)V+0
J 1207 C1 org.fusesource.lmdbjni.Transaction.close()V (5 bytes) @ 0x00007f12093dd024 [0x00007f12093dcf00+0x124]
j  com.tesco.mewbase.doc.impl.lmdb.LmdbDocManager$LmdbReadStream.close()V+22
~~~~

Here's the test, if you want to run it yourself:

https://github.com/Tesco/mewbase/blob/doc_query/src/test/java/com/tesco/mewbase/doc/impl/lmdb/LmdbDocManagerTest.java#L47

(be sure to uncomment the repeat line so it runs in a loop and also uncomment the tx.close line)

When I comment out the tx.close() the tests run fine but I'm not sure that is a wise thing to do (leaking resources?)

**Comment by krisskross** [comment] 2016-11-18 10:42
The reader locktable slots of each transaction is tied to the thread that created it. So I think what happens is that the transactions are not closed by the right thread. You can change this behavior by setting the NOTLS flag. This will tie reader locktable slots to transaction objects instead of to threads.

```java
Env env = new Env();
env.open(dbDir.getPath(), Constants.NOTLS);
```

**Comment by purplefox** [comment] 2016-11-18 10:57
@krisskross thanks for your quick reply.

I tried disabling TLS as suggested (I have committed this on same branch as above), but I am still seeing the same core dump

**Comment by krisskross** [comment] 2016-11-18 11:11
Hmm. I cannot reproduce with your change. But I get a few exceptions related to file descriptors. Maybe there is something in the test that make LMDB core dump for some reason?

```java
java.lang.IllegalStateException: failed to create a child event loop

	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:133)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:122)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:118)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:34)
	at io.vertx.core.Vertx.vertx(Vertx.java:80)
	at com.tesco.mewbase.MewbaseTestBase.setup(MewbaseTestBase.java:42)
	at com.tesco.mewbase.doc.DocManagerTest.setup(DocManagerTest.java:39)
	at com.tesco.mewbase.MewbaseTestBase.before(MewbaseTestBase.java:38)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:95)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.run(TestContextImpl.java:122)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.access$600(TestContextImpl.java:30)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:221)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:194)
	at io.vertx.ext.unit.junit.VertxUnitRunner$3.evaluate(VertxUnitRunner.java:211)
	at io.vertx.ext.unit.junit.RepeatRule$RepeatStatement.evaluate(RepeatRule.java:32)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:157)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 48 more
Caused by: java.io.IOException: Too many open files
	at sun.nio.ch.IOUtil.makePipe(Native Method)
	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65)
	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:155)
	... 52 more


java.lang.IllegalStateException: Worker executor closed

	at io.vertx.core.impl.WorkerExecutorImpl.executeBlocking(WorkerExecutorImpl.java:65)
	at io.vertx.core.WorkerExecutor.executeBlocking(WorkerExecutor.java:61)
	at com.tesco.mewbase.doc.impl.lmdb.LmdbDocManager.close(LmdbDocManager.java:106)
	at com.tesco.mewbase.doc.DocManagerTest.tearDown(DocManagerTest.java:49)
	at com.tesco.mewbase.MewbaseTestBase.after(MewbaseTestBase.java:47)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:95)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.run(TestContextImpl.java:122)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.access$600(TestContextImpl.java:30)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:221)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$3.evaluate(VertxUnitRunner.java:217)
	at io.vertx.ext.unit.junit.RepeatRule$RepeatStatement.evaluate(RepeatRule.java:32)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by purplefox** [comment] 2016-11-18 11:13
Did you make sure you uncommented the tx.close line before running?

Also what OS are you using? I am Linux x86_64

The error you get above is not related to the issue here, you will get that eventually if you run in a loop long enough.

**Comment by krisskross** [comment] 2016-11-18 11:18
Yes the tx.close is uncommented and the test repeats 1000 times.

I'm using Arch Linux x86_64.

**Comment by krisskross** [comment] 2016-11-18 11:20
Could it be a race condition where Env or Database is closed before the transaction closes?

**Comment by purplefox** [comment] 2016-11-18 11:50
Good catch :) That seems to be the problem, attempting to use an transaction/iterator on a closed database.

Just a thought, it might be nice if the Java layer could manage the state of the database object and throw an IllegalStateException if an attempt to use a tx/iterator on a closed db is made. I was getting scare for a minute I might have to load up the core dump and remember my C again (it has been many years!) ;)

**Comment by krisskross** [comment] 2016-11-18 11:59
Nice! Yes, that's a good idea.

I should let you know about [lmdbjava](https://github.com/lmdbjava/lmdbjava) which me and Ben Alex created a while ago. It uses JNR-FFI instead of hawtjni (in order to be somewhat future proof to Project Panama) and has a few more extra checks and validations (that can be turned off also), ByteBuffer support etc. 

I'm not sure the project is as battle tested as lmdbjni just yet. But you might want to check that out also.

**Comment by purplefox** [comment] 2016-11-18 12:38
Would you recommend lmdbjava over lmdbjni?

**Comment by krisskross** [comment] 2016-11-18 12:54
Yes. Its feature complete and our intention is to spend more time on lmdbjava and make it production ready. Also JNR-FFI seems safer than HawtJNI since its no longer maintained. They are roughly the same in performance. However, you must use direct ByteBuffers at the moment (we have a fix for byte arrays). 

But I don't know how it much production time it has (I think Ben is using it). So there might be bugs. I know quite a few are using lmdbjni, including my company. 

It's up to you to decide.

**Closed** 2016-11-18 19:28 UTC
